### ISSUE TITLE
run GMPS with special gain settings

### ISSUE THREAD

**Issue by gnperdue** [fermilab-accelerator-ai/meetings#20]
Run GMPS with special gain settings during special run type leading up to the accelerator turn on

* zero gain

**Comment by gnperdue** [comment]
These runs were taken and Kiyomi is analyzing the data.

**Comment by jasonstjohn** [comment]
This running happened Oct 15th, 2019 from 1pm to  3:45 pm. Many power supplies thought to influence GMPS regulation, mainly Main Injector but also Switchyard beam lines with nearby power supplies, were not operating.

**Comment by gnperdue** [comment]
This happened and Kiyomi has the data.
